[build-system]
requires = ["setuptools>=68.2.2", "wheel>=0.41.2"]
build-backend = "setuptools.build_meta"

[project]
name = "imdb-sentiment-api"
version = "0.1.0"
description = "IMDB Sentiment Analysis API"
requires-python = ">=3.9,<3.10" 