services:
  - type: web
    name: imdb-sentiment-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    autoDeploy: true 