services:
  - type: web
    name: imdb-sentiment-api
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd api && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: POETRY_VERSION
        value: 1.4.2
    autoDeploy: true 